package:
  name: ess 
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: .. 

requirements:
  build:
    - python {{ python }}
  run:
    - python {{ python }}
    - scipp
    - fabio
    - tifffile
    # TODO scipp-neutron (no dependency yet)

test:
  imports:
    - scipp
    - ess
    - ess.v20
    - ess.v20.imaging
  requires:
    - pytest
  source_files:
    - ess/
  commands:
    - python -m pytest -v

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

about:
  home: https://github.com/scipp/ess
  license: GPLv3
  summary: Neutron scattering tools for the European Spallation Source (ESS) 
  description: Neutron scattering tools for Data Reduction bespoke to ESS facility and instruments 
  dev_url: https://github.com/scipp/ess
  doc_url: 
