parameters:
  - name: release
    type: boolean
    default: False

jobs:
  - job: "documentation"
    displayName: "Documentation"
    pool:
      vmImage: "ubuntu-latest"
    variables:
      documentation_artefact_path: "$(Build.StagingDirectory)/documentation"
      documentation_repo_path: "$(Build.StagingDirectory)/git"
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: "current"
          specificBuildWithTriggering: true
          downloadType: "single"
          artifactName: "documentation"
          downloadPath: "$(Build.StagingDirectory)"
        displayName: "Retrieve updated documentation"
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
          sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSPwLMTtzQ4Jgm/Vhc0L1upLgBvnxH8Qreb95hN/jdkUwpSCtbHG8HzG/u52cbibEVlc+UT4txUEP8G6samcHWh5DxitmrSSWMDIr5c0KWlMxck++E1mbpKsMNhU359GQmqxvZZqukdsFDqN3wMhM4HDHyV7Ztkz+k5rmGzTdwJSQ3MhvNVNHBUtyF7GGmvLO3gNJiE+c8U8bgjdTUZY1wtQyOBMe1w/cyW0x3CI5crYA4/y1frcDQrRQAd8dzeR2Pxsx9Te2EnPxrhCvo+RvGs4Y57SsZTm2v1igASjulYJstQ8mHAW6btlNoVQwnIDfCaXOpmU1gxcMr5j6eFYJI0/RM3mwtBOm+LhksA3NZ1uAygBElpGAreYRu/LyW3qA6ZywrRqdp1xI4uBqN+Po3bYaLPBIj5cJDSAPvMdtwmn+nt2QLPy0aRBtyl/eDBtwri/1Az2EjCjN8uoKz5moV4t0rrQP0FVj0Bdmgrvw5s9MClzPHcCkuB7raFj1FHX9SRMoHFOSqk53wsuwGDwQI5kN1dBSAQ5t88iYYILgO7+tXxu8ORS/Pe8xMKzR+6J/j0RqkM1TCcF1WyTZ/4ZzUCvuI724FNplliOVgEaorVZV3R7LTrEp3UthXG0/GuN07RHwRGUJL07KGEEHKS7oOxP+xZ8hjoPMxmzWLXujBUQ=="
          sshKeySecureFile: "azure-ess-key"
        displayName: "Add GitHub Pages deploy key"
      - bash: |
          set -ex
          # Publishing documentation involves a Git commit, this sets the identity for that commit
          git config --global user.name 'The Great Documentation Generation Entity'
          git config --global user.email 'nobody@localhost'
        displayName: "Git config"
      - bash: |
          set -ex
          git clone git@github.com:scipp/ess "$(documentation_repo_path)"
        displayName: "Clone documentation repository"
      - bash: |
          set -ex
          cd "$(documentation_repo_path)"
          # checkout the gh-pages branch
          git checkout gh-pages
          # Stage removal of everything
          git rm -rf .
          git status
          # Unstage deletion of and recover "release" directory
          git reset -- release || true
          git checkout -- release || true
          git status
        displayName: "Remove old documentation, keeping releases"
      - bash: |
          set -ex
          cd "$(documentation_repo_path)"
          # The .nojekyll file is used to turn off GitHub Pages building
          touch .nojekyll
          rsync -av "$(documentation_artefact_path)/" .
          git add .
          git status
        displayName: "Copy new documentation"
      - bash: |
          set -ex
          release_docs_dir="release/$(git describe --tags)"
          cd "$(documentation_repo_path)"
          mkdir -p "$release_docs_dir"
          rsync -av "$(documentation_artefact_path)/" "$release_docs_dir"
          git add .
          git status
        condition: and(succeeded(), ${{ parameters.release }})
        displayName: "Copy new documentation for release"
      - bash: |
          set -ex
          cd "$(documentation_repo_path)"
          # Amend last commit to keep repository size down
          git commit --amend --date="$(date)" --message='Auto commit from CI'
          git status
          git push --force-with-lease
          git status
        displayName: "Push to GitHub Pages"
