parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

# Note: the 'endpoint' refers to the Azure service connection, which can be
# found on the Azure pipelines web interface under
# scipp > scippneutron > Settings > Service connections

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: allow_for_ess_pipeline
  pipelines:
  - pipeline: upstream_scippneutron_release
    project: scippneutron
    source: Release
    trigger: true

trigger:
  - use_shared_pipelines # HACK change to main

pr: none

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    conda_channels: '--channel scipp'
    gh_pages_subdirectory: 'ess'
    config:
      noarch:
        py_versions: ['3.7']
        conda_env: 'ess-developer-stable.yml'
    deploy: true
    conda_label: 'next' # TODO change to dev
    publish_docs: false
