parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

# Note: the 'endpoint' refers to the Azure service connection, which can be
# found on the Azure pipelines web interface under
# scipp > ess > Settings > Service connections

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: main

trigger:
  tags:
    include:
      - '*.*.*'

pr: none

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    conda_channels: '--channel scipp'
    gh_pages_subdirectory: 'ess'
    config:
      linux:
        py_versions: ['noarch']
        conda_env: 'ess-developer.yml'
    deploy: true
    conda_label: 'main'
    release: true
